### ISSUE TITLE
Почему-то сервер отвечает 415 ответом при проверке платежа

### ISSUE THREAD

**Issue by highfeed** [ortexx/walletone#1]
Что может быть?

**Comment by ortexx** [comment]
Можно поподробнее? Какой конкретно запрос отправляется (url, данные и.т.д)

**Comment by highfeed** [comment]
Для проверки оплаты стоит адрес site.ru/pay/check1

В express
```
router.post('/check1', (req, res) => {
  console.log(req)
})
```

В логах

```
POST /pay/check1 415 4.322 ms - 1859
POST /pay/check1 415 4.934 ms - 1859
```

Делаю
```
router.post('/check1', w1.notify(successHandler, errorHandler))
```

Получаю тоже самое в логах

Как вообще отловить данные, которые отправляет W1? 

Тут скорее вопрос в целом, а не конкретно к модулю.

**Comment by ortexx** [comment]
Первое что бросается в глаза, написано, что проверка оплаты на  site.ru/pay/check1
А в экпрессе стоит обработчик на /check1, вместо /pay/check1

По поводу моего модуля. successHandler - должна быть передана функция. которая выполнится если никаких ошибок нет, errorHandler - то же самое для ошибки.

Я не являюсь официальным представителем компании walletone. Для большего понимания как у них все работает можно ознакомиться с этим для начала:

https://www.walletone.com/ru/merchant/documentation/#step5

**Comment by highfeed** [comment]
1. Там все ок, это роутинг express. Через postman когда вызываю - запрос доходит - когда приходит запрос от W1 то 415 ответ.

2. С функциями тоже все ок:
```
let successHandler = (data) => {
  f(data)
  return db.payments.findOne({_id: +data.WMI_PAYMENT_NO, status: 'create'}).then(payment => {
    if (!payment) {
      return false
    }
    payment.status = 'success'
    payment.info = data
    payment.payment_at = new Date()
    return payment.save()
  })
}

let errorHandler = () => {
  return Promise
}

router.post('/check1', (req, res) => {
  f(req)
})

router.post('/check', w1.notify(successHandler, errorHandler))

router.get('/pay/success', (req, res) => {
  res.render('payment_true')
})

router.get('/pay/fail', (req, res) => {
  res.render('payment_false')
})
```

**Comment by ortexx** [comment]
Ошибка 415 может возникать если запрос был, например, неправильно составлен в отношении заголовка content-type.

Поинтересуйтесь у поддержки w1, наверняка они с таким уже сталкивались.

**Comment by highfeed** [comment]
Я закомментировал это и ошибка 415 пропала.

```
// app.use(bodyParser.json())
// app.use(bodyParser.urlencoded({extended: false}))
```

Но функция success пока не работает.

**Comment by highfeed** [comment]
Нашел причину. body-parser не умеет обрабатывать кодировку, которую присылает W1

```
Sun, 23 Apr 2017 13:52:41 GMT body-parser:urlencoded content-type "application/x-www-form-urlencoded; charset=windows-1251"
Sun, 23 Apr 2017 13:52:41 GMT body-parser:urlencoded invalid charset
```

**Comment by highfeed** [comment]
Но теперь я не могу понять почему у меня ошибка
```
 Error: Wrong signature
```
И у тебя в функции ошибки нет аргумента с body. Как дебажить-то?

**Comment by ortexx** [comment]
Мидлвейр в экспрессе это просто функция. ты можешь написать что-то типа того:
```
router.post('/check1', (req, res, next) => {
     console.log(req.body)
     w1.notify(successHandler, errorHandler)(req, res, next);
})
```

**Comment by highfeed** [comment]
О, спасибо. А ты есть в Telegram?

**Comment by highfeed** [comment]
Ну, все данные приходят нормальными. Форма генерируется, платеж проходит. А все равно:

```
Error: Wrong signature`
```

**Comment by ortexx** [comment]
Скинь полностью все то. что приходит в теле запроса. req.body

**Comment by highfeed** [comment]
```
{ WMI_AUTO_ACCEPT: '1',
  WMI_AUTO_LOCATION: '1',
  WMI_COMMISSION_AMOUNT: '0.04',
  WMI_CREATE_DATE: '2017-04-23 14:39:01',
  WMI_CURRENCY_ID: '643',
  WMI_DESCRIPTION: 'Donate #36',
  WMI_EXPIRED_DATE: '2017-05-23 14:39:01',
  WMI_FAIL_URL: 'https://site.ru/pay/fail/',
  WMI_LAST_NOTIFY_DATE: '2017-04-23 14:50:43',
  WMI_MERCHANT_ID: '141310823280',
  WMI_NOTIFY_COUNT: '6',
  WMI_ORDER_ID: '340078218097',
  WMI_ORDER_STATE: 'Accepted',
  WMI_PAYMENT_AMOUNT: '1.00',
  WMI_PAYMENT_NO: '36',
  WMI_PAYMENT_TYPE: 'WalletOneRUB',
  WMI_SUCCESS_URL: 'https://site.ru/pay/success/',
  WMI_TO_USER_ID: '192156975641',
  WMI_UPDATE_DATE: '2017-04-23 14:39:59',
  WMI_SIGNATURE: 'RgVxbFtUqrzQ/o/nldpxcg==' }
```

**Comment by ortexx** [comment]
Я кое-что изменил в коде, попробуй обовиться. Если не поможет - то без ключа я никак не смогу проверить сигнатуру на правильность

Мой телеграм @Ortex

**Comment by highfeed** [comment]
Проблема решена! Спасибо :)
