### ISSUE TITLE
Метод формирования подписи.

### ISSUE THREAD

**Issue by feed4rz** [ortexx/walletone#2]
Стоит добавить метод формирования подписи как опцию при инициализации. Сейчас в WalletOne доступно 3 метода:
 - Без формирования
 - MD5
 - SHA1

**Comment by ortexx** [comment]
Без формирования не вижу смысла делать.  
добавил метод **.setAlgorithm**

```
setAlgorithm('md5');
setAlgorithm('sha1');
```
