### ISSUE TITLE
how do i validated the payment? in express

### ISSUE THREAD

**Issue by Cariaga** [ortexx/walletone#3]
- is WMI_SUCCESS_URL the only end point? if so how do i validate that on success is not fake does walletone pass any parameter to WMI_SUCCESS_URL
- is the signature passed over the WMI_SUCCESS_URL?

`const busboy = require('express-busboy');
const notifyRouter = busboy.extend(express.Router());
const W1 = require("walletone");
let defaultData = {
    WMI_SUCCESS_URL: 'https://mysite/success/',
    WMI_FAIL_URL: 'https://mysite/fail/',
};

let secretKey = "mykey";
let merchantId = "mymerchantid";

const w1 = new W1(secretKey, merchantId, defaultData);

let successHandler = (data, callback) => {
  // data === req.body    
  // save payment info in db e.t.c    
  // callback() or return promise
  console.log("Must finish here");
};

let errorHandler = (err, meta) => {
  // you can save something to a file, db e.t.c.
  // operation must be synchronous or in the background 
};

notifyRouter.get('/', w1.notify(successHandler, errorHandler));

app.use('/notification', notifyRouter);

app.get('/fail', function (req, res) {
  console.log(req);
  res.sendStatus(501);
});

app.get('/success', function (req, res) {
  
});

app.get('/Pay2', function (req, res) {
  // Create form data
  let PaymentNumber = getRandomInt(0,10000);
  w1.setAlgorithm("md5");
  
  let fields = w1.getFormFields({
      WMI_PAYMENT_AMOUNT: '10',
      WMI_PAYMENT_NO:PaymentNumber,
      WMI_CURRENCY_ID: '840',
      WMI_DESCRIPTION: 'Recharge',
      WMI_EXPIRED_DATE: '2020-12-31T23:59:59',
      WMI_CUSTOMER_EMAIL: 'user@example.com',
      WMI_AUTO_LOCATION: "1"
      // ...and other options
  });

  var createInput = function(name, value){
    return '<input name="' + name + '" value="' + value + '">';
  };
  let resultfeild="";
  for(let i=0;i<fields.length;++i){
    resultfeild+=createInput(fields[i].name,fields[i].value);
  }
  console.log(resultfeild);
  let form = '<form method="POST" action="https://wl.walletone.com/checkout/checkout/Index" accept-charset="UTF-8">'+resultfeild+'<input type="submit"></form>';
  res.send(form);
});`

**Comment by ortexx** [comment]
Hi. The point to check is the __/notification__, not WMI_SUCCESS_URL. The library does all the checks itself.  In cases of mismatch of secret shared hash or any other issue, __errorHandler__ function is called, otherwise __successHandler__. WMI_SUCCESS_URL and WMI_FAIL_URL options is necessary just to redirect user.

**Comment by Cariaga** [comment]
i'm not receiving any call /notification or do i need to call /notification? if thats the case then my error is WMI_RESULT=RETRY&WMI_DESCRIPTION=Wrong%20signature

`const W1 = require("walletone");
let secretKey = "";
let merchantId = "";
let defaultData = {
  WMI_SUCCESS_URL: 'https://mysite.com/success/',
  WMI_FAIL_URL: 'https://mysite.com/fail/',
};
const w1 = new W1(secretKey, merchantId, defaultData);

app.get('/Pay',function(req,res){

// Create form data
  let fields = w1.getFormFields({
    WMI_PAYMENT_AMOUNT: '10',
    WMI_CURRENCY_ID: '840',
    WMI_DESCRIPTION: 'Recharge',
    WMI_CUSTOMER_EMAIL: 'user@example.com',
    WMI_AUTO_LOCATION: "1"
    // ...and other options
  });
  console.log(fields);  // returns sorted fields and signature too
  var createInput = function(name, value){
    return '<input name="' + name + '" value="' + value + '">';
  };
  let result = "";
  for(var i =0;i<fields.length;++i){
    result+=createInput(fields[i].name,fields[i].value);
  }
  res.send('<form method="POST" action="https://wl.walletone.com/checkout/checkout/Index" accept-charset="UTF-8">' + result + '<input type="submit"></form>');
});

const busboy = require('express-busboy');
const notifyRouter = busboy.extend(express.Router());
let successHandler = (data, callback) => {
    // data === req.body    
    // save payment info in db e.t.c    
    // callback() or return promise
    console.log("Should be called");
};
 
let errorHandler = (err, meta) => {
    // you can save something to a file, db e.t.c.
    // operation must be synchronous or in the background 
};
notifyRouter.post('/', w1.notify(successHandler, errorHandler));
app.use('/notification', notifyRouter);

app.get('/success',function(req,res,next){
  w1.notify(successHandler, errorHandler)(req, res, next);
 //res.sendStatus(200);
});
app.get('/fail',function(req,res){
});
`

**Comment by ortexx** [comment]
You have to __set__ "yourServer/notification" as notification url in walletone account settings. They will call this endpoint automatically when it is necessary.

**Comment by Cariaga** [comment]
it now works but i'm receiving an error of 

UnsupportedMediaTypeError: unsupported charset "WINDOWS-1251"
--
  | at urlencodedParser (/opt/app-root/src/node_modules/body-parser/lib/types/urlencoded.js:108:12)
  | at Layer.handle [as handle_request] (/opt/app-root/src/node_modules/express/lib/router/layer.js:95:5)
  | at trim_prefix (/opt/app-root/src/node_modules/express/lib/router/index.js:317:13)
  | at /opt/app-root/src/node_modules/express/lib/router/index.js:284:7
  | at Function.process_params (/opt/app-root/src/node_modules/express/lib/router/index.js:335:12)
  | at next (/opt/app-root/src/node_modules/express/lib/router/index.js:275:10)
  | at logger (/opt/app-root/src/node_modules/morgan/index.js:144:5)
  | at Layer.handle [as handle_request] (/opt/app-root/src/node_modules/express/lib/router/layer.js:95:5)
  | at trim_prefix (/opt/app-root/src/node_modules/express/lib/router/index.js:317:13)
  | at /opt/app-root/src/node_modules/express/lib/router/index.js:284:7

**Comment by ortexx** [comment]
You have to use busboy instead of body-parser for notification handling. Look at the readme

**Comment by Cariaga** [comment]
i've ordered my code and put on top of everything it may have something to do with cors or websocket 
i still receiving but i guess i could ignore it as long as i'm getting my notifications correctly

 `let secretKey = "484639536c5d766e767c5734474f455a5b344337305348635f5966";
let merchantId = "190887657209";
let defaultData = {
  WMI_SUCCESS_URL: 'https://tester-holdem-server.4b63.pro-ap-southeast-2.openshiftapps.com/success/',
  WMI_FAIL_URL: 'https://tester-holdem-server.4b63.pro-ap-southeast-2.openshiftapps.com/fail/',
};
const w1 = new W1(secretKey, merchantId, defaultData);

let successHandler = (data, callback) => {
  // data === req.body    
  // save payment info in db e.t.c    
  // callback() or return promise
  //console.log("Should be called "+beautify(data,null ,2 ,100));
  if(data.WMI_ORDER_STATE=="Accepted"){
    console.log("Accepted Payment Process here ");
    console.log("PayAmount "+data.WMI_PAYMENT_AMOUNT);
    console.log("Reciver UUID "+data.UserAccountID);//custom parameter
  }

  callback();
};



let errorHandler = (err, meta) => {
console.log("failed "+err);
  // you can save something to a file, db e.t.c.
  // operation must be synchronous or in the background 
};

notifyRouter.post('/', w1.notify(successHandler, errorHandler));
app.use('/notification', notifyRouter);
`
